[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "sort-networks-mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.6.0.dev2025090805,<26"
mojo = ">=0.25.6.0.dev2025091000,<0.26"
